updated with network switch
Cerebellum-Network/laboratory-ui pull request #4
Opened 2021-03-16 11:24 UTC by karthikeyan-cere

Added network switch and added to the friendly bot.

2021-03-16 13:38 UTC, evgeny-s requested changes

2021-03-16 13:38 UTC, evgeny-s commented on src/components/network/Network.tsx
> +    "TESTNET": "wss://testnet-node-1.cere.network:9944",
Let's use enum here.
Also move it to the separate file

2021-03-16 13:38 UTC, evgeny-s commented on src/components/network/Network.tsx
> +          value="TESTNET"
Use enum here

2021-03-16 13:38 UTC, evgeny-s commented on src/components/network/Network.tsx
>        <div className="tab d-flex justify-content-end m-3  ">
Use `.map` rendering here:
```
enumKeys.map((item) => (
   <>
     <input itemValue />
     <label>itemLabel</label>
   </>
))
```

2021-03-16 13:38 UTC, evgeny-s commented on src/modules/network/reducers.ts
> +  network: 'TESTNET',
Use enum here

2021-03-16 13:38 UTC, evgeny-s commented on src/services/LaboratoryApiService.ts
> +  postFriendBotAssetRequest = async (destination: string, network: string) => {
string -> enum

2021-03-18 05:41 UTC, karthikeyan-cere commented on src/components/network/Network.tsx
> +    "TESTNET": "wss://testnet-node-1.cere.network:9944",
Fixed

2021-03-18 05:41 UTC, karthikeyan-cere commented on src/components/network/Network.tsx
> +          value="TESTNET"
Fixed

2021-03-18 05:41 UTC, karthikeyan-cere commented on src/modules/network/reducers.ts
> +  network: 'TESTNET',
Fixed

2021-03-18 05:42 UTC, karthikeyan-cere commented on src/services/LaboratoryApiService.ts
> +  postFriendBotAssetRequest = async (destination: string, network: string) => {
Fixed

2021-03-18 12:04 UTC, karthikeyan-cere commented on src/components/network/Network.tsx
>        <div className="tab d-flex justify-content-end m-3  ">
fixed.

2021-03-18 12:36 UTC, evgeny-s requested changes

2021-03-18 12:36 UTC, evgeny-s commented on src/components/network/network.enum.ts
> +export enum Networks {
Do we need this?

2021-03-18 12:36 UTC, evgeny-s commented on src/components/network/networkProvider.enum.ts
> +export enum NetworksProvider {
Do we need this?

2021-03-18 12:38 UTC, karthikeyan-cere commented on src/components/network/network.enum.ts
> +export enum Networks {
deleted.

2021-03-18 12:38 UTC, karthikeyan-cere commented on src/components/network/networkProvider.enum.ts
> +export enum NetworksProvider {
deleted.

2021-03-18 14:00 UTC, evgeny-s approved these changes

2021-03-18 14:10 UTC, merged